### ISSUE TITLE
Opam entry is out of date

### ISSUE THREAD

**Issue by shawnw** [jfeser/combinat#1]
Opam only has 1.0 available, not 2.0.

**Comment by jfeser** [comment]
I'll try to get the opam package updated. If you want to use the current version, you can always pin it with `opam pin add https://github.com/jfeser/combinat.git`.

Out of curiosity, what are you using this library for?

**Comment by shawnw** [comment]
>Out of curiosity, what are you using this library for?

I didn't want to write my own combination-generating code for an ocaml answer to one of this week's perl weekly challenge problems (https://perlweeklychallenge.org/blog/perl-weekly-challenge-085/), and this was the first useful-looking library I found.

**Comment by jfeser** [comment]
https://github.com/ocaml/opam-repository/pull/21113

Better late than never, I guess
